travis:
  secure:
    BINSTAR_TOKEN: a00t4jD1mOGiWnJ0c1i8mpCpJeuB+OiY5uPci/PrkMa31GVJd3g8QYcyRnMXP3b9QmZbumNlRWXxoduK79KYVXfnUIk1oae5aocoPHJZQaUpV42Ij2jV8twW8L+qKar3oPkhfiebO3ek5lAP7QVJGarKlGlyTTX6sAwaboOVcPAjPV0CRc14yDauLq/PHwizvq2UvJIJKZWHj5mmp/biIBpHRhU750/5W+k6+pykF7dBnx+hNzcy98tsX//cFdpRO1Bznyu86xiKiq0iSFdS8bHL4OpNU2uRwuh1qPWsbiTY2TAZXlr1iAwC/OV3ow0j6V6FgexJk23GSAt8oRY9+pnnr3yIQpCbcN5si0VEN5urdXhp1k54sqOUcsv27TftetBTrEb9ZxM/IYVqttJ+OhMYKkGQrPmj/WcgZvFH1UPMTdGvLJPm0sOcPWXFI8xPxAWTRT+qaLxZZoYaHJUbbW6lpgIWUUZvnq1ij9AjwihwFgJAzOAsEKQlrrCHEggvwjBA87tv/dKhEYaD4HmnSNDkEoq4hdWig7Dv/2tz9N/wPdeanjTXTawkfB4YR69OLrHrvqgr4Fa/B+fOCU8n8M05ZXj8Y+ZWSG7+q+exTyouKWBCXpCrR4bN1/90ZYVOMBq7o6/Ah9XTshQv/l1FehQDfmyO6rUqc7rMlqzKDh0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
