travis:
  secure:
    BINSTAR_TOKEN: eRUcpkTyoWyXWASd3g4zy3JwfPPZtk65WfWru0wncBIHfByDsnYoVJnhsyO+mWd/jL3QPsXshX29M1uDL4mph+9jn54EBF6DTmjHJgiabFzcy9imHSw/yZbi+maapyh0pe5NhhhibG4HUqY/SfAoNz96PaIXO92i+YsD0ZKa4ZnbomxZKgFsbpcYfNsL6zPAXTIveDHdaoRfCowDCICqG9gHmaKAoOkNyuBdz5+y64BSTSnBkfO9uVfDg+DXTGwB98IGBjSZImKiNpueTUXTBxlFuSjrD3vFx9UZKeMLcpZk+AmTtvbLYWrgHWhTs9BH72Hz1CmNRcVT3hfbLICe31XXTF4bY3Q4RXyb16K5ifWOaMw4n+3oz1OJViBUysJWOoD3mYX8TN8DpHYbm03TuJ5m4/Ec+Pq3tD6IIwDPvILjD8w5bzvZ79KCSmfSp32G935c4rFTG0AgHPqCKHByryPnv/YOZJ2qkVmTg90mciBZndrnngAoRi5TCqCT8xjcziiGYb/WmHxRXXHlzI4FHrffBim2n5+2TiCdIRyDckXNaDJ2aLzQ2xvwtLX+LR5ZyM/ZeawWlHOe0K5JFaZbc3Z5bTf8+GNZT35sIeqGXV213fo3nqAHxhwMS/CO+7I3PyoRFc0k2J5zsBIXAw4dIFMXjiI14h/KK1Vy8EwjE2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
